-- Preserve stock/put/call exposure composition for CUSIP-aggregated 13F rows.
ALTER TABLE "Holding"
  ADD COLUMN IF NOT EXISTS "stockShares" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "stockValue" DECIMAL(18, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "putShares" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "putValue" DECIMAL(18, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "callShares" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "callValue" DECIMAL(18, 2) NOT NULL DEFAULT 0;
